logging:
  level:
    org.springframework: debug
spring:
  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: username
      password: passw0rd
  jpa:
    show-sql: true
    h2:
      console:
        enabled: true